services:
  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en1a-users:latest
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - monitor-net
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yovi
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://localhost,http://localhost:3000,http://localhost:80,http://20.251.170.191

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://20.251.170.191:3000
        - VITE_GAMEY_URL=http://20.251.170.191:4000
        - VITE_GAMEY_API_URL=http://20.251.170.191:3001
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en1a-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
      - gamey-service
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en1a-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  gamey-service:
    build: ./gameyapi
    container_name: gamey-service
    image: ghcr.io/arquisoft/yovi_en1a-gameyapi:latest
    ports:
      - "3001:3001"
    environment:
      - GAMEY_RUST_URL=http://gamey:4000 
      - MONGODB_URI=mongodb://mongodb:27017/yovi
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - gamey
      - mongodb
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  mongodb:
    image: mongo:latest
    container_name: yovi_mongodb
    ports:
      - "27017:27017"
    networks:
      - monitor-net
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo_data: